#! /bin/bash

echo ""
echo "Now building..."
echo ""
middleman build
echo ""

echo ""
# read -p "commit message: " commitmessage
# echo ""
cd build
git add -A #assuming your .gitignore is configured
# git commit -m "$commitmessage"
git commit -m "update blog"
git push

read -p "Open? (y/n) " push
if [ "$push" == "y" ]; then
  chrome http://crushandcreate.com
else
  echo ""
fi